[package]
name = "blademaster"
version = "0.1.0"
description = "A text-based roguelike game"
authors = ["Maxwell Anderson <maxwell.brayden.anderson@gmail.com>"]
edition = "2018"
repository = "https://github.com/Maxgy/blademaster"
license = "MIT"

[dependencies]
legion = "0.2"
termion = "1.5"
tui = "0.8"